### ISSUE TITLE
Add registers to improve performance and usability

### ISSUE THREAD

**Issue by RobTillaart** [m5stack/M5Unit-8Encoder#1]
Recently I bought a M5Unit-8Encoder and I am quite satisfied with it. 
There are a few points that would improve the usability and performance of the product.

### Changed register for rotary encoders

As I2C does not provide interrupts, polling the 8 rotary encoders is the only way to see if a change has occurred. 
(multiple master is also an option however far more difficult)

Would it be possible to add one register = 1 byte = 8 bits to indicate a specific channel has changed since last reading the channel?
Then polling would require much less I2C handling, as with only 5 bytes over I2C one could check all 8 channels for change.
Then it takes another 8 per channel to get the new value. 
Currently polling all 8 channels (individually) takes 64 bytes, and yes that includes having the new value. 
Even a bulk fetch would take ~36 bytes (assuming you want only abs or rel values)

Depending on the project, and the update frequency of the 8 channels it would reduce the IO.
- 0 channels changed => factor ~13
- 1 channel changed => factor ~4
- 2 channels changed => factor ~3
- 3 channels changed => factor ~2
etc.
And yes at some point checking the **change** register will take more time. 

(Register 0x61 ?)

### One Button register (to read them all)

A similar byte register would be useful for checking the 8 buttons in one call.
These 8 states could be merged into one byte so checking them can be done more efficient too.
This would roughly speed up the IO with a factor 2.

(Register 0x62 ?)

### Button toggle count since last read

It would be useful to have a register to see how often a button was pressed and released since it was last read. 
This would allow one to capture otherwise missed button presses and prevent heavy polling.
A bit like the behavior of the incremental registers for the RE.

(Register 0x58..0x5F would be a nice place to store up to 250 button presses)

### Update possible?

Q: Related to the above, is it possible to upgrade a module?

Thank you for your time
Rob

**Comment by phd0** [comment]
yes I love your idea.
Look [here](https://github.com/m5stack/M5Unit-8Encoder-Internal-FW) to find the firmware source code.
If you can create code with STM32, you'll be happy.
Me, I'm too new to STM32,

**Comment by RobTillaart** [comment]
@phd0 
Thanks for the link, I will have a look.

**Comment by RobTillaart** [comment]
### Changed register for rotary encoders

A global **uint8_t g_changed = 0** needs to be allocated, somewhere around line 60-70.

(~495) **void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)** could set the change bit per rotary encoder.

**void i2c2_receive_callback(uint8_t \*rx_data, uint16_t len)** needs to serve the new register e.g. 0x61
just after this block serving register 0x60 ** else if (len == 1 && (rx_data[0] == 0x60))**
it needs to reset the g_changed to zero after reading.

conclusion: possible to implement

### One Button register (to read them all)

The buttons are read upon request, see **else if (len == 1 && ((rx_data[0] >= 0x50) & (rx_data[0] <= 0x57)))**

A polling of "new register" 0x62 could read all buttons in one call and return a byte to have all states. 
Need a loop over **uint8_t read_button_switch_status(uint8_t offset)** or so.

conclusion: possible to implement

### Button toggle count since last read

As there is no IRQ serving the button presses (as far as I see), so this could be more complex as a new ISR should be made.
Also the reset of the counter should be implemented when either reading the toggle counter or when reading the state.

conclusion: need more knowledge of STM32 interrupts to do this (incl bouncing etc)

**Comment by chenzhjie** [comment]
Thank you for your suggestion, it's a great idea. I have modified the STM32 firmware [M5Unit-8Encoder-Internal-FW](https://github.com/m5stack/M5Unit-8Encoder-Internal-FW/releases/tag/2.0) implement the above functionality.

**Comment by RobTillaart** [comment]
@chenzhjie @phd0 
Working on a PR for my Arduino library to support the new V2 Firmware registers
- https://github.com/RobTillaart/M5ROTATE8/pull/7

(need to find appropriate hardware to test)

**Comment by RobTillaart** [comment]
@chenzhjie 

Is there a document describing how to update the firmware of the M5Unit-8Encoder?
Thanks for your time!
